export const menu: Array<MenuType> = [
  { id: '0', divide: '대용량', product: '빽사이즈 아메리카노(ICED)' },
  { id: '1', divide: '대용량', product: '빽사이즈 원조커피(ICED)' },
  { id: '2', divide: '대용량', product: '빽사이즈 원조커피 제로슈거(ICED)' },
  { id: '3', divide: '대용량', product: '빽사이즈 달콤아이스티(ICED)' },
  { id: '4', divide: '대용량', product: '빽사이즈 아이스티샷 추가(ICED)' },
  { id: '5', divide: '대용량', product: '빽사이즈 빽`s 카페라떼(ICED)' },
  { id: '6', divide: '대용량', product: '빽사이즈 초코라떼(ICED)' },
  { id: '7', divide: '커피', product: '아메리카노(HOT)' },
  { id: '8', divide: '커피', product: '아메리카노(ICED)' },
  { id: '9', divide: '커피', product: '빽`s 카페라떼(HOT)' },
  { id: '10', divide: '커피', product: '빽`s 카페라떼(ICED)' },
  { id: '11', divide: '커피', product: '원조커피(HOT)' },
  { id: '12', divide: '커피', product: '원조커피(ICED)' },
  { id: '13', divide: '커피', product: '원조커피 제로슈거(HOT)' },
  { id: '14', divide: '커피', product: '원조커피 제로슈거(ICED)' },
  { id: '15', divide: '커피', product: '바닐라라떼(HOT)' },
  { id: '16', divide: '커피', product: '바닐라라떼(ICED)' },
  { id: '17', divide: '커피', product: '카페모카(HOT)' },
  { id: '18', divide: '커피', product: '카페모카(ICED)' },
  { id: '19', divide: '커피', product: '캬라멜마키아또(HOT)' },
  { id: '20', divide: '커피', product: '캬라멜마키아또(ICED)' },
  { id: '21', divide: '커피', product: '달달연유라떼(HOT)' },
  { id: '22', divide: '커피', product: '달달연유라떼(ICED)' },
  { id: '23', divide: '커피', product: '아이스티샷추가(ICED)' },
  { id: '24', divide: '커피', product: '블랙펄 카페라떼+노란빨대(ICED)' },
  { id: '25', divide: '커피', product: '바나나 카페라떼(HOT)' },
  { id: '26', divide: '커피', product: '바나나 카페라떼(ICED)' },
  { id: '27', divide: '커피', product: '콜드브루(HOT)' },
  { id: '28', divide: '커피', product: '콜드브루(ICED)' },
  { id: '29', divide: '커피', product: '골드브루라떼(HOT)' },
  { id: '30', divide: '커피', product: '골드브루라떼(ICED)' },
  { id: '31', divide: '커피', product: '콜드브루 흑당라떼(HOT)' },
  { id: '32', divide: '커피', product: '콜드브루 흑당라떼(ICED)' },
  { id: '33', divide: '커피', product: '콜드브루 연유라떼(HOT)' },
  { id: '34', divide: '커피', product: '콜드브루 연유라떼(ICED)' },
  { id: '35', divide: '디카페인', product: '디카페인 콜드브루(HOT)' },
  { id: '36', divide: '디카페인', product: '디카페인 콜드브루(ICED)' },
  { id: '37', divide: '디카페인', product: '디카페인 콜드브루라떼(HOT)' },
  { id: '38', divide: '디카페인', product: '디카페인 콜드브루라떼(ICED)' },
  { id: '39', divide: '디카페인', product: '디카페인 콜드브루 흑당라떼(HOT)' },
  { id: '40', divide: '디카페인', product: '디카페인 콜드브루 흑당라떼(ICED)' },
  { id: '41', divide: '디카페인', product: '디카페인 콜드브루 연유라떼(HOT)' },
  { id: '42', divide: '디카페인', product: '디카페인 콜드브루 연유라떼(ICED)' },
  { id: '43', divide: '음료', product: '딸기라떼+노란빨대(ICED)' },
  { id: '44', divide: '음료', product: '뱅쇼(HOT)' },
  { id: '45', divide: '음료', product: '뱅쇼(ICED)' },
  { id: '46', divide: '음료', product: '꿀밤라떼(HOT)' },
  { id: '47', divide: '음료', product: '꿀밤라떼(ICED)' },
  { id: '48', divide: '음료', product: '바나나라떼(HOT)' },
  { id: '49', divide: '음료', product: '바나나라떼(ICED)' },
  { id: '50', divide: '음료', product: '초코라떼(HOT)' },
  { id: '51', divide: '음료', product: '초코라떼(ICED)' },
  { id: '52', divide: '음료', product: '녹차라떼(HOT)' },
  { id: '53', divide: '음료', product: '녹차라떼(ICED)' },
  { id: '54', divide: '음료', product: '토피넛라떼(HOT)' },
  { id: '55', divide: '음료', product: '토피넛라떼(ICED)' },
  { id: '56', divide: '음료', product: '민트초코라떼(HOT)' },
  { id: '57', divide: '음료', product: '민트초코라떼(ICED)' },
  { id: '58', divide: '음료', product: '수정과(HOT)' },
  { id: '59', divide: '음료', product: '수정과(ICED)' },
  { id: '60', divide: '음료', product: '식혜(ICED)' },
  { id: '61', divide: '음료', product: '미숫가루(ICED)' },
  { id: '62', divide: '음료', product: '미숫가루(우유)(ICED)' },
  { id: '63', divide: '음료', product: '미숫가루(두유)(ICED)' },
  { id: '64', divide: '음료', product: '밀크티(HOT)' },
  { id: '65', divide: '음료', product: '밀크티(ICED)' },
  { id: '66', divide: '음료', product: '블랙펄라떼+노란빨대(ICED)' },
  { id: '67', divide: '음료', product: '블랙펄밀크티+노란빨대(ICED)' },
  { id: '68', divide: '음료', product: '아이스크러시 멜론(ICED)' },
  { id: '69', divide: '음료', product: '아이스크러시 오렌지(ICED)' },
  { id: '70', divide: '음료', product: '아이스크러시 콜라(ICED)' },
  { id: '71', divide: '음료', product: '아이스크러시 파인애플(ICED)' },
  { id: '72', divide: '티', product: '청포도플라워(ICED)' },
  { id: '73', divide: '티', product: '아이스미초(석류)(ICED)' },
  { id: '74', divide: '티', product: '달콤아이스티(ICED)' },
  { id: '75', divide: '티', product: '깔라만시티(HOT)' },
  { id: '76', divide: '티', product: '깔라만시티(ICED)' },
  { id: '77', divide: '티', product: '레몬티(HOT)' },
  { id: '78', divide: '티', product: '레몬티(ICED)' },
  { id: '79', divide: '티', product: '자몽티(HOT)' },
  { id: '80', divide: '티', product: '자몽티(ICED)' },
  { id: '81', divide: '티', product: '유자티(HOT)' },
  { id: '82', divide: '티', product: '유자티(ICED)' },
  { id: '83', divide: '티', product: '피치우롱스위티(HOT)' },
  { id: '84', divide: '티', product: '피치우롱스위티(ICED)' },
  { id: '85', divide: '티', product: '우롱티(HOT)' },
  { id: '86', divide: '티', product: '우롱티(ICED)' },
  { id: '87', divide: '티', product: '페퍼민트티(HOT)' },
  { id: '88', divide: '티', product: '페퍼민트티(ICED)' },
  { id: '89', divide: '티', product: '황금캐모마일티(HOT)' },
  { id: '90', divide: '티', product: '황금캐모마일티(ICED)' },
  { id: '91', divide: '티', product: '레몬얼그레이티(HOT)' },
  { id: '92', divide: '티', product: '레몬얼그레이티(ICED)' },
  { id: '93', divide: '티', product: '오렌지자몽블랙티(HOT)' },
  { id: '94', divide: '티', product: '오렌지자몽블랙티(ICED)' },
  { id: '95', divide: '에이드&주스', product: '깔라만시에이드(ICED)' },
  { id: '96', divide: '에이드&주스', product: '쿨라임에이드(ICED)' },
  { id: '97', divide: '에이드&주스', product: '미초(석류)에이드(ICED)' },
  { id: '98', divide: '에이드&주스', product: '레모네이드(ICED)' },
  { id: '99', divide: '에이드&주스', product: '자몽에이드(ICED)' },
  { id: '100', divide: '에이드&주스', product: '청포도에이드(ICED)' },
  { id: '101', divide: '에이드&주스', product: '유자에이드(ICED)' },
  { id: '102', divide: '에이드&주스', product: '복숭아에이드(ICED)' },
  { id: '103', divide: '에이드&주스', product: '딸기에이드+노란빨대(ICED)' },
  { id: '104', divide: '에이드&주스', product: '소울트로닉에이드(ICED)' },
  { id: '105', divide: '에이드&주스', product: '체리콕콕(ICED)' },
  { id: '106', divide: '에이드&주스', product: '블루캔디소다(ICED)' },
  { id: '107', divide: '에이드&주스', product: '제주감귤주스(ICED)' },
  { id: '108', divide: '에이드&주스', product: '완전블루베리주스(ICED)' },
  { id: '109', divide: '에이드&주스', product: '완전토마토주스(ICED)' },
  { id: '110', divide: '에이드&주스', product: '완전망고주스(ICED)' },
  { id: '111', divide: '에이드&주스', product: '완전파인애플주스(ICED)' },
  { id: '112', divide: '에이드&주스', product: '완전딸기주스(ICED)' },
  { id: '113', divide: '빽스치노', product: '딸기바나나빽스치노(ICED)' },
  { id: '114', divide: '빽스치노', product: '초코바나나빽스치노(ICED)' },
  { id: '115', divide: '빽스치노', product: '녹차빽스치노(ICED)' },
  { id: '116', divide: '빽스치노', product: '원조빽스치노(ICED)' },
  { id: '117', divide: '빽스치노', product: '피스타치오빽스치노(ICED)' },
  { id: '118', divide: '빽스치노', product: '민트초코빽스치노(ICED)' },
  { id: '119', divide: '빽스치노', product: '쿠키크런치빽스치노(ICED)' },
  { id: '120', divide: '빽스치노', product: '초코빽스치노(ICED)' },
  { id: '121', divide: '빽스치노', product: '딸기빽스치노(ICED)' },
  { id: '122', divide: '블렌디드', product: '퐁당치노(바닐라)+노란빨대(ICED)' },
  { id: '123', divide: '블렌디드', product: '퐁당치노(원조커피)+노란빨대(ICED)' },
  { id: '124', divide: '블렌디드', product: '퐁당치노(미숫가루)+노란빨대(ICED)' },
  { id: '125', divide: '블렌디드', product: '블루베리요거트스무디(ICED)' },
  { id: '126', divide: '블렌디드', product: '플레인요거트스무디(ICED)' },
  { id: '127', divide: '블렌디드', product: '딸기요거트스무디(ICED)' },
  { id: '128', divide: '블렌디드', product: '밀크쉐이크(ICED)' },
  { id: '129', divide: '블렌디드', product: '블루캔디밀크쉐이크(ICED)' },
  { id: '130', divide: '블렌디드', product: '바나나밀크쉐이크(ICED)' },
  { id: '131', divide: '블렌디드', product: '바나나커피쉐이크(ICED)' },
  { id: '132', divide: '디저트', product: '잼있는 사라다빵(디저트)' },
  { id: '133', divide: '디저트', product: '빽그램핫도그(디저트)' },
  { id: '134', divide: '디저트', product: '못난이 생크림 카스텔라(디저트)' },
  { id: '135', divide: '디저트', product: '고메버터 소금빵(디저트)' },
  { id: '136', divide: '디저트', product: '청양고추 소금빵(디저트)' },
  { id: '137', divide: '디저트', product: '명란 소금빵(디저트)' },
  { id: '138', divide: '디저트', product: '쫀득 감자빵(디저트)' },
  { id: '139', divide: '디저트', product: '쫀득 고구마빵(디저트)' },
  { id: '140', divide: '디저트', product: '황치즈 크럼블 머핀(디저트)' },
  { id: '141', divide: '디저트', product: '크리미슈(디저트)' },
  { id: '142', divide: '디저트', product: '크리미단팥빵(디저트)' },
  { id: '143', divide: '디저트', product: '맛카롱(순우유)(디저트)' },
  { id: '144', divide: '디저트', product: '맛카롱(딸기크런치)(디저트)' },
  { id: '145', divide: '디저트', product: '맛카롱(초코크런치)(디저트)' },
  { id: '146', divide: '디저트', product: '순삭쿠키(코코아더블초코)(디저트)' },
  { id: '147', divide: '디저트', product: '순삭쿠키(청키초코)(디저트)' },
  { id: '148', divide: '디저트', product: '순삭쿠키(청키화이트 초코)(디저트)' },
  { id: '149', divide: 'MD상품', product: '콜드브루 원액' },
  { id: '150', divide: 'MD상품', product: '디카페인 콜드브루 원액' },
];